modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="remote_test"
version="1.0.0"
displayName="remote test"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="hardy, MCreator"

[[dependencies.remote_test]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




